# Generated by Django 5.0.2 on 2024-02-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phote',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
